### ISSUE TITLE
[RuntimeError] Unknown / unsupported VS version '17.0'

### ISSUE THREAD

**Issue by XEL-Maker** [isaac-sim/IsaacSim-ros_workspaces#2]
Hello, I faced with RuntimeError "Unknown / unsupported VS version '17.0'"

I install Ros2-Foxy follow [the ros2 windows install instructions](https://ms-iot.github.io/ROSOnWindows/GettingStarted/SetupRos2.html#installing-ros-2-binaries)

Here is my environment information for re-produce error

OS: Window 11 Pro 22H2
ROS2 Distributor: Foxy
ROS2 Location: C:\opt\ros\foxy
WorkSpace Location: C:\foxy_ws
VisualStudio: Microsoft **Visual Studio Community 2022** (64-bit) Ver 17.4.3
Command Prompt: Visual Studio 2022 Developer Command Prompt v17.4.3

command prompt
```
cd C:\foxy_ws
rosdep install -i --from-path src --rosdistro foxy -y
rosdep update
colcon build
```
error print
```
c:\foxy_ws>colcon build
[0.369s] root DEBUG Using proactor: IocpProactor
Starting >>> carter_description
[0.377s] colcon.colcon_ros.prefix_path.catkin WARNING The path 'C:\opt\ros\foxy\x64\tools\vcpkg\installed\x64-windows' in the environment variable CMAKE_PREFIX_PATH doesn't exist
Starting >>> carter_navigation
Starting >>> isaac_ros2_messages
Starting >>> isaac_ros_navigation_goal
Starting >>> isaac_tutorials
--- stderr: isaac_ros2_messages
Traceback (most recent call last):
  File "c:\opt\ros\foxy\x64\lib\site-packages\colcon_core\executor\__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "c:\opt\ros\foxy\x64\lib\site-packages\colcon_core\task\__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "c:\opt\ros\foxy\x64\lib\site-packages\colcon_ros\task\ament_cmake\build.py", line 59, in build
    rc = await extension.build(
  File "c:\opt\ros\foxy\x64\lib\site-packages\colcon_cmake\task\cmake\build.py", line 87, in build
    rc = await self._reconfigure(args, env)
  File "c:\opt\ros\foxy\x64\lib\site-packages\colcon_cmake\task\cmake\build.py", line 162, in _reconfigure
    raise RuntimeError(
RuntimeError: Unknown / unsupported VS version '17.0'
---
Failed   <<< isaac_ros2_messages [0.06s, exited with code 1]
Aborted  <<< carter_description [0.11s]
Aborted  <<< carter_navigation [0.08s]
Aborted  <<< isaac_ros_navigation_goal [0.05s]
Aborted  <<< isaac_tutorials [0.03s]

Summary: 0 packages finished [0.25s]
  1 package failed: isaac_ros2_messages
  4 packages aborted: carter_description carter_navigation isaac_ros_navigation_goal isaac_tutorials
  1 package had stderr output: isaac_ros2_messages
Unknown / unsupported VS version '17.0'

c:\foxy_ws>
```
thanks in advance

**Comment by XEL-Maker** [comment]
I already solve this porblem by uninstall VisualStudio2022 and install VisualStudio2019.
But i don't close this issue.
