### ISSUE TITLE
Closed Build failed, module 'em' has no attribute 'BUFFERED_OPT'

### ISSUE THREAD

**Issue by Creador270** [isaac-sim/IsaacSim-ros_workspaces#8]
Following the instructions of [https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_ros.html#isaac-ros-workspace](url) at the moment to make the `colcon build` I got the following error:

> Of Note: I'm using pyenv by the way and was doing the `colcon build` in humble_ws\

```Starting >>> carter_navigation
Starting >>> custom_message
Starting >>> isaac_ros2_messages
Starting >>> isaac_ros_navigation_goal
Starting >>> isaac_tutorials
Starting >>> isaacsim
Starting >>> iw_hub_navigation
Finished <<< isaac_ros_navigation_goal [0.98s]                                                                                         
Finished <<< carter_navigation [2.00s]                                                                                                 
--- stderr: custom_message                                                                                                           
CMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(~/.pyenv/shims/python3 -m rosidl_adapter
  --package-name custom_message --arguments-file
  ~/Omniverse/IsaacSim-ros_workspaces/humble_ws/build/custom_message/rosidl_adapter__arguments__custom_message.json
  --output-dir
  ~/Omniverse/IsaacSim-ros_workspaces/humble_ws/build/custom_message/rosidl_adapter/custom_message
  --output-file
  ~/Omniverse/IsaacSim-ros_workspaces/humble_ws/build/custom_message/rosidl_adapter/custom_message.idls)
  returned error code 1:

  AttributeError processing template 'msg.idl.em'

  Traceback (most recent call last):

    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 51, in evaluate_template
      em.BUFFERED_OPT: True,

  AttributeError: module 'em' has no attribute 'BUFFERED_OPT'

  

  During handling of the above exception, another exception occurred:

  

  Traceback (most recent call last):

    File "~/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "~/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 39, in convert_msg_to_idl
      expand_template('msg.idl.em', data, output_file, encoding='iso-8859-1')
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 23, in expand_template
      content = evaluate_template(template_name, data)
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 69, in evaluate_template
      _interpreter.shutdown()

  AttributeError: 'NoneType' object has no attribute 'shutdown'

Call Stack (most recent call first):
  /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:23 (rosidl_generate_interfaces)


---
Failed   <<< custom_message [2.04s, exited with code 1]
Aborted  <<< iw_hub_navigation [2.03s]
Aborted  <<< isaacsim [2.03s]
Aborted  <<< isaac_tutorials [2.06s]
Aborted  <<< isaac_ros2_messages [2.22s]                           

Summary: 2 packages finished [2.51s]
  1 package failed: custom_message
  4 packages aborted: isaac_ros2_messages isaac_tutorials isaacsim iw_hub_navigation
  2 packages had stderr output: custom_message isaac_ros2_messages´´´

I fixed installing `pip3 install empy==3.3.2`, It was on the 4.3 version.
Before I was having an error related to `lark` but it was solved here [https://github.com/cyberbotics/webots_ros2/issues/183](url)
After that, everything was compiled successfully.

**Comment by ReubenLimMonash** [comment]
I faced the above issues as well when installing on WSL2 (Ubuntu 22). The above steps resolved it for me as well. Thanks.
